# Generated by Django 5.1 on 2024-08-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('composition', models.CharField(max_length=500)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('category', models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milkshake'), ('PA', 'Paneer'), ('IC', 'Icecream'), ('GH', 'Ghee'), ('CH', 'Cheese'), ('LS', 'Lassi'), ('MK', 'Milk')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
